amqp:
  dsn: "amqp://user:password@localhost:5672/"

clickhouse:
  dsn: "clickhouse://user:password@localhost:9000/db"

svc:
  total: 100000
  eps: 100000
  workers: 8
  report_dir: '/home/nts/projects/test-model/reports2'