amqp:
  dsn: "amqp://user:password@localhost:5672/"

clickhouse:
  dsn: "clickhouse://user:password@localhost:9000/db"

svc:
  total: 100
  eps: 100
  workers: 4
  report_dir: '/home/nts/projects/test-model/reports2'